<a href="https://colab.research.google.com/github/ECV21/data-science-portafolio/blob/main/1A_Resoluci%C3%B3n_de_problemas_Aplicaciones_de_%C3%A1lgebra_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##By Eduardo Cruz

## Ejercicio 1

Un inversionista le afirma a su corredor de bolsa que todas sus acciones pertenecen a tres compañías: Aeroméxico, Volaris y Vivaaerobus, y que hace dos días su valor bajó 350 pero que ayer aumentó 600. El corredor recuerda que hace dos días el precio de las acciones de Aeroméxico bajó 1 por cada una, mientras que las de Volaris bajaron 1.50, pero que el precio de las acciones de Vivaaerobus subió 0.50. También recuerda que ayer el precio de las acciones de Aeroméxico subió 1.50 por acción, el de las de Volaris bajo otros 0.50 por acción y las de Vivaaerobus subieron 1. **Demuestre que el corredor no cuenta con la información suficiente para calcular el número de acciones que posee la inversionista en cada compañía, pero que si ella dice tener 280 acciones de Vivaaerobus, el corredor pueda calcular el número de acciones que posee en Aeromexico y en Volaris.**

In [4]:
import sympy as sp

"""
Aquí vamos a definir las variables:

x: número de acciones de Aeroméxico
y: número de acciones de Volaris
z: número de acciones de Vivaaerobus
"""
x, y, z = sp.symbols('x y z')

# Ecuaciones iniciales
eq1 = sp.Eq(-1*x - 1.5*y + 0.5*z, -350)
eq2 = sp.Eq(1.5*x - 0.5*y + 1*z, 600)

# intento de solución, se aplica una solución infinita
sol_infinita = sp.solve((eq1, eq2), (x, y, z), dict=True) #téoricamente nos damos cuenta que no hay solución única
print("No hay solución única, solo una solución general:", sol_infinita)

#solucionar sistema sabiendo que z = 280
eq1_z = eq1.subs(z, 280)
eq2_z = eq2.subs(z, 280)
sol_con_z = sp.solve((eq1_z, eq2_z), (x, y))
print("Solución conociendo z=280:", sol_con_z)

No hay solución única, solo una solución general: [{x: 390.909090909091 - 0.454545454545455*z, y: 0.636363636363636*z - 27.2727272727273}]
Solución conociendo z=280: {x: 263.636363636364, y: 150.909090909091}


##Ejercicio 2

Considere el siguiente diagrama de una malla de calles de un sentido con vehículos que entran y salen de las intersecciones. La intersección k se denota por [k], k = 1,2,3,4. Las flechas a lo largo de las calles indican la dirección del flujo del tráfico. Sea xi el número de vehículos que circulan por la calle i. Suponiendo que el tráfico que entra a una intersección también sale, establezca un sistema de ecuaciones que describa el diagrama del flujo de tráfico.


In [ ]:
#Definimos nuesteas variables usando simpy
x1,x2,x3,x4,x5 = sp.symbols('x1 x2 x3 x4 x5')

#esta sería nuestro panteamiento de problemas
eq1 = sp.Eq(x1 + x5 + 100, x3 + 300)   # (1)
eq2 = sp.Eq(x1 + x2, 400)              # (2)
eq3 = sp.Eq(x2 + x3, x4 + 100)         # (3)
eq4 = sp.Eq(x4, x5 + 100)              # (4)

#como no tenemos una solución única, planteariamos una solución general
sol_general = sp.solve([eq1, eq2, eq3, eq4], (x1,x2,x3,x4,x5), dict=True)
print("Es la solución general debido a que no tien solución única:")
print(sol_general)

#en el caso de cerrar de [1] a [3]; es decir, x3=0
sol_x3_0 = sp.solve([eq1.subs(x3,0), eq2, eq3.subs(x3,0), eq4], (x1,x2,x4,x5), dict=True)
print("")
print("Suponiendo que x3 = 0 :")
print(sol_x3_0)

#aquí suponemos que x=3 y x5=0; se cerralos estas calles
sol_x3x5_0 = sp.solve([eq1.subs({x3:0,x5:0}), eq2.subs(x5,0), eq3.subs({x3:0,x5:0}), eq4.subs(x5,0)],
                      (x1,x2,x3,x4,x5), dict=True)
print("")
print("Este es el resultado cuando suponemos que x3=0 y x5=0:")
print(sol_x3x5_0)


Es la solución general debido a que no tien solución única:
[{x1: x3 - x5 + 200, x2: -x3 + x5 + 200, x4: x5 + 100}]

Suponiendo que x3 = 0 :
[{x1: 200 - x5, x2: x5 + 200, x4: x5 + 100}]

Este es el resultado cuando suponemos que x3=0 y x5=0:
[{x1: 200, x2: 200, x4: 100}]


##Ejercicio 3.

 Utilice la inversa de matrices para codificar un mensaje asignado en clase de forma personalizada. Se utilizarán arreglos de tamaño 3 y la siguiente matriz de 3×3.

In [5]:
import numpy as np

#Definimos el alfabeto en orden como lo supone el ejercicio
alfabeto = "ZABCDEFGHIJKLMNOPQRSTUVWXY"  # Z=0, A=1, ..., Y=25

#creamos un diccionario de letra y su respectivo número
letra_a_num = {letra: i for i, letra in enumerate(alfabeto)}
#creamos un diccionario del número con su respectiva letra
num_a_letra = {i: letra for i, letra in enumerate(alfabeto)}


#creamos una función que convirte un texto en mayúsculars a lista de números
def texto_a_numeros(texto):
    return [letra_a_num[ch] for ch in texto.upper() if ch in letra_a_num]

#creamos una función que convierte lista de números a texto
def numeros_a_texto(numeros):
    return "".join(num_a_letra[n] for n in numeros)


#DEFINIMOS la matriz A, su inversa mod 26
A = np.array([[2,4,3],
              [0,1,-1],
              [3,5,7]])

#Calculamos la det de la matriz y después su matriz mod26
det = int(round(np.linalg.det(A)))
det_mod = det % 26

# inverso modular del determinante
def inverso_mod(a, m):
    for x in range(1, m):
        if (a * x) % m == 1:
            return x
    raise ValueError(f"Esta matriz no tiene inverso mod {m}")

det_inv = inverso_mod(det_mod, 26)

#Calculamos la adjunta de A
adj = np.round(det * np.linalg.inv(A)).astype(int)

#Calculamos la inversa modular
A_inv = (det_inv * adj) % 26

print("Matriz A:\n", A)
print("Determinante:", det, " ≡", det_mod, " (mod 26)")
print("Inversa modular A^-1:\n", A_inv)



##CReamos la función para encriptar y desencriptar nuestro texto
def hill_cipher(my_texto, matriz):
    """Cifra o descifra un texto según la matriz (A o A_inv)."""
    nums = texto_a_numeros(my_texto)

    #agregamos el num CERO en caso de que nuermo sea impar
    while len(nums) % 3 != 0:
        nums.append(0)

    nums_out = []
    for i in range(0, len(nums), 3):
        bloque = np.array(nums[i:i+3])
        cifrado = np.dot(matriz, bloque) % 26
        nums_out.extend(cifrado)

    return numeros_a_texto(nums_out)

#aplicamos nuestra función usando nuestro texto
mensaje = "MENSAJESECRETOHOLAPROFESORABRICEYDAESUNGUSTOESTARENSUCLASE"

print("\nMensaje original:\n", mensaje)

# Encriptar
cifrado = hill_cipher(mensaje, A)
print("\nTexto encriptado:\n", cifrado)

# Desencriptar
descifrado = hill_cipher(cifrado, A_inv)
print("\nTexto desencriptado:\n", descifrado)


Matriz A:
 [[ 2  4  3]
 [ 0  1 -1]
 [ 3  5  7]]
Determinante: 3  ≡ 3  (mod 26)
Inversa modular A^-1:
 [[ 4 13 15]
 [25 19 18]
 [25 18 18]]

Mensaje original:
 MENSAJESECRETOHOLAPROFESORABRICEYDAESUNGUSTOESTARENSUCLASE

Texto encriptado:
 JQFTQBWNOOMDTGICKHSCIKLTAQLYICWFAAVZHGZYBYKJNQSHTQUARAGHRJZO

Texto desencriptado:
 MENSAJESECRETOHOLAPROFESORABRICEYDAESUNGUSTOESTARENSUCLASEZZ


##ejercico 4.

En una región la población se mantiene constante y esta se divide en rural y urbana. Se ha observado que cada año, 25% de habitantes de la zona rural pasa a la urbana y 5% de la urbana se cambia a la rural. Si al inicio de un experimento para determinar el movimiento de una población se tienen 8 millones en la zona rural y 2 en la zona urbana.


In [ ]:
import numpy as np

#matriz inicial
A = np.array([[0.75, 0.05],
              [0.25, 0.95]])

#vector de poblacion, en millones
x0 = np.array([8.0, 2.0])

# aquí calculamos los Eigenvalores y eigenvectores
eigvals, eigvecs = np.linalg.eig(A)

# Autovectores para λ=1 y λ=0.7
v1 = np.array([1.0, 5.0])   # autovector para λ = 1
v2 = np.array([1.0, -1.0])  # autovector para λ = 0.7
P = np.column_stack((v1, v2))
Pinv = np.linalg.inv(P)

# Verificación de la diagonalización
D = Pinv @ A @ P

# Coeficientes de la combinación lineal de v1 y v2
coeffs = Pinv @ x0
alpha, beta = coeffs

#definimos los años a proyectar
n = 100
D_pow = np.diag([1.0, 0.7**n])
A_pow_via_diag = P @ D_pow @ Pinv

# Alternativa: potencia directa de la matriz
A_pow_direct = np.linalg.matrix_power(A, n)

# Estado después de n años
x_n_via_diag = A_pow_via_diag @ x0
x_n_direct = A_pow_direct @ x0

# Estado límite (n→∞)
steady_state = alpha * v1

# Mostrar resultados
print("Matriz A:")
print(A)
print("\nEigenvalores:")
print(eigvals)
print("\nAutovectores (columnas):")
print(eigvecs)
print("\nMatriz P (autovectores ordenados [v1, v2]):")
print(P)
print("\nP^{-1} A P = D:")
print(D)
print("\nCoeficientes (alpha, beta):", alpha, beta)
print("\nPoblación después de", n, "años (via diagonalización):")
print(x_n_via_diag)
print("\nPoblación después de", n, "años (via potencia directa):")
print(x_n_direct)
print("\nEstado límite (n→∞):")
print(steady_state)
print("\nProporciones límite:")
print("Rural:", steady_state[0] / steady_state.sum(),
      "Urbana:", steady_state[1] / steady_state.sum())


Matriz A:
[[0.75 0.05]
 [0.25 0.95]]

Eigenvalores:
[0.7 1. ]

Autovectores (columnas):
[[-0.70710678 -0.19611614]
 [ 0.70710678 -0.98058068]]

Matriz P (autovectores ordenados [v1, v2]):
[[ 1.  1.]
 [ 5. -1.]]

P^{-1} A P = D:
[[1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 7.00000000e-01]]

Coeficientes (alpha, beta): 1.6666666666666667 6.333333333333334

Población después de 100 años (via diagonalización):
[1.66666667 8.33333333]

Población después de 100 años (via potencia directa):
[1.66666667 8.33333333]

Estado límite (n→∞):
[1.66666667 8.33333333]

Proporciones límite:
Rural: 0.16666666666666669 Urbana: 0.8333333333333334


##ejercicio 5

HAcer operaciones con la siguiente matriz
    [4, 11, 14],
    [8, 7, -2]

In [6]:
import numpy as np

#Definimos la matriz inicial
A = np.array([
    [4, 11, 14],
    [8, 7, -2]
], dtype=float)

print("Matriz A:\n", A)

# (a) Calcular A^T A
A_TA = A.T @ A
print("\n(a) Matriz A^T A:\n", A_TA)

# (b) Valores propios de A^T A (orden creciente)
eigvals, eigvecs = np.linalg.eig(A_TA)
idx = np.argsort(eigvals)  # índices para ordenar
eigvals_sorted = eigvals[idx]
eigvecs_sorted = eigvecs[:, idx]
print("\n(b) Valores propios de A^T A (orden creciente):\n", eigvals_sorted)

# (c) Valores singulares de A
sing_vals = np.sqrt(eigvals_sorted)
print("\n(c) Valores singulares de A:\n", sing_vals)

# (d) Base ortonormal de R^3 compuesta por vectores propios de A^T A
# Normalizamos los vectores propios
V_ortonormal = eigvecs_sorted / np.linalg.norm(eigvecs_sorted, axis=0)
print("\n(d) Base ortonormal de R^3 (vectores propios normalizados):\n", V_ortonormal)

# (e) Matrices U, Σ, V de la SVD
U, Sigma, Vt = np.linalg.svd(A)
print("\n(e) Matriz U:\n", U)
print("\n(e) Matriz Σ (diagonal con valores singulares):\n", np.diag(Sigma))
print("\n(e) Matriz V^T:\n", Vt)

# (f) Verificación A = U Σ V^T
Sigma_full = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma_full, Sigma)
A_reconstruida = U @ Sigma_full @ Vt
print("\n(f) Reconstrucción de A (U Σ V^T):\n", A_reconstruida)

# Verificar si son iguales (con tolerancia numérica)
if np.allclose(A, A_reconstruida):
    print("\n La igualdad A = U Σ V^T se cumple.")
else:
    print("\n La igualdad no se cumple.")


Matriz A:
 [[ 4. 11. 14.]
 [ 8.  7. -2.]]

(a) Matriz A^T A:
 [[ 80. 100.  40.]
 [100. 170. 140.]
 [ 40. 140. 200.]]

(b) Valores propios de A^T A (orden creciente):
 [-3.71123759e-15  9.00000000e+01  3.60000000e+02]

(c) Valores singulares de A:
 [        nan  9.48683298 18.97366596]

(d) Base ortonormal de R^3 (vectores propios normalizados):
 [[-0.66666667 -0.66666667 -0.33333333]
 [ 0.66666667 -0.33333333 -0.66666667]
 [-0.33333333  0.66666667 -0.66666667]]

(e) Matriz U:
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]

(e) Matriz Σ (diagonal con valores singulares):
 [[18.97366596  0.        ]
 [ 0.          9.48683298]]

(e) Matriz V^T:
 [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]

(f) Reconstrucción de A (U Σ V^T):
 [[ 4. 11. 14.]
 [ 8.  7. -2.]]

 La igualdad A = U Σ V^T se cumple.


/tmp/ipython-input-2044521392.py:23: RuntimeWarning: invalid value encountered in sqrt
  sing_vals = np.sqrt(eigvals_sorted)
